name: Deploy Laravel to FTP server

on: workflow_dispatch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2.34.1
        with:
          php-version: "8.3"
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4.2.3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Store secrets
        run: |
          echo "${{ secrets.DOTENV_PROD }}" > .env
          echo "${{ secrets.GAPI_SERVICE_ACCOUNT }}" > storage/secrets/service-account.json
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ vars.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
