name: Deploy Laravel to FTP server

on: workflow_dispatch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Setup nodejs
        uses: actions/setup-node@v4
      - name: Store secrets
        run: |
          mkdir storage/secrets
          echo '${{ secrets.DOTENV_PROD }}' > .env
          echo '${{ secrets.GAPI_SERVICE_ACCOUNT }}' > storage/secrets/service-account.json
      - name: Build Vite
        run: |
          npm install
          npm run build
          rm -r node_modules/
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ vars.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ vars.FTP_SERVER_DIR }}
      - name: Install Composer packages and Optimize Laravel
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.SSH_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          script: |
            cd ${{ vars.FTP_SERVER_DIR }}
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('sha384', 'composer-setup.php') === 'dac665fdc30fdd8ec78b38b9800061b4150413ff2e3b6f88543c636f7cd84f6db9189d43a81e5503cda447da73c7e5b6') { echo 'Installer verified'.PHP_EOL; } else { echo 'Installer corrupt'.PHP_EOL; unlink('composer-setup.php'); exit(1); }"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"
            php composer.phar install --prefer-dist --no-progress
            php artisan optimize
